enum IND_SERVICES {
  BIOMETRICS = 'bio',
  COLLECT_DOCUMENTS = 'doc',
  RETURN_VISA = 'tkv',
  RESIDENCE_ENDORSEMENT_STICKER = 'vaa',
}

enum IND_SERVICES_LABELS {
  bio = 'BIOMETRICS',
  doc = 'COLLECT DOCUMENTS',
  tkv = 'RETURN VISA',
  vaa = 'RESIDENCE ENDORSEMENT STICKER',
}

export { IND_SERVICES_LABELS };
export default IND_SERVICES;
