enum IND_SERVICES {
  BIOMETRICS = 'bio',
  COLLECT_DOCUMENTS = 'doc',
  RETURN_VISA = 'tkv',
  RESIDENCE_ENDORSEMENT_STICKER = 'vaa',
}

enum IND_SERVICES_LABELS {
  BIO = 'BIOMETRICS',
  DOC = 'COLLECT DOCUMENTS',
  TKV = 'RETURN VISA',
  VAA = 'RESIDENCE ENDORSEMENT STICKER',
}

export { IND_SERVICES_LABELS };
export default IND_SERVICES;
